<?php
echo '<div id="overlayer"></div>';
echo '<div class="loader">';
echo '<div class="spinner-border text-primary" role="status">';
echo '<span class="sr-only">Та түр хүлээнэ үү...</span>';
echo '</div>';
echo '</div>';
echo '<div class="site-mobile-menu site-navbar-target">';
echo '<div class="site-mobile-menu-header">';
echo '<div class="site-mobile-menu-close mt-3">';
echo '<span class="icon-close2 js-menu-toggle"></span>';
echo '</div>';
echo '</div>';
echo '<div class="site-mobile-menu-body"></div>';
echo '</div>';
echo '<header class="site-navbar js-sticky-header site-navbar-target" role="banner">';
echo '';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '';
echo '<div class="col-6 col-xl-2">';
echo '<h1 class="mb-0 site-logo"><a href="index.php" class="h2 mb-0"><span class="text-primary">Jet</span><span class="text-primary-jet">Finance</span></a></h1>';
echo '</div>';
echo '';
echo '<div class="col-12 col-md-10 d-none d-xl-block">';
echo '<nav class="site-navigation position-relative text-right" role="navigation">';
echo '';
echo '<ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">';
echo '';
echo '';
echo '';
echo '<li class="has-children">';
echo '<a href="#services-section" class="nav-link">Зээлийн бүтээгдэхүүн</a>';
echo '<ul class="dropdown">';
echo '<li><a href="#services-section" class="nav-link">Хэрэглээний зээл</a></li>';
echo '<li><a href="#services-section" class="nav-link">Автомашин худалдан авах зээл</a></li>';
echo '<li><a href="#services-section" class="nav-link">Бизнесийн зээл</a></li>';
echo '<li><a href="#services-section" class="nav-link">Шуурхай зээл</a></li>';
echo '<li><a href="#services-section" class="nav-link">Бизнесийн зээлийн шугам</a></li>';
echo '<li><a href="#services-section" class="nav-link">Итгэлцэлийн үйлчилгээ</a></li>';
echo '';
echo '</ul>';
echo '</li>';
echo '';
echo '';
echo '<li><a href="#ser-section" class="nav-link">Үйлчилгээ</a></li>';
echo '<li><a href="#blog-section" class="nav-link">Мэдээ мэдээлэл</a></li>';
echo '<li><a href="#about-section" class="nav-link">Бидний тухай</a></li>';
echo '<li><a href="#contact-section" class="nav-link">Холбоо барих</a></li>';
echo '<li class="social"><a href="#contact-section" class="nav-link"><span class="icon-facebook"></span></a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '';
echo '';
echo '<div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a></div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</header>';
?>