<?php
echo '<section class="site-section border-bottom" id="services-section">';
echo '<div class="container">';
echo '<div class="row mb-5">';
echo '<div class="col-12 text-center" data-aos="fade">';
echo '<h2 class="section-title mb-3">Зээлийн бүтээгдэхүүн</h2>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row align-items-stretch">';
echo '';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/001-wallet.svg"  class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Хэрэглээний зээл</h3>';
echo '<p>Иргэд болон ААН-үүдэд зориулсан энэхүү бүтээгдэхүүнээрээ та бүхэнд автомашинаа барьцаалан санхүүгийн хэрэгцээгээ хангах боломжийг олгож байна.</p>';
echo '<p><a class="btn btn-primary btn-md text-white" href="products/p1.php">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="100">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/business.svg" class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Бизнесийн зээл</h3>';
echo '<p>Жижиг дунд бизнес эрхлэгчдийн эргэлтийн хөрөнгийг нэмэгдүүлэх, үйл ажиллагааны цар хүрээг өргөтгөх боломжийг олгож байна.</p>';
echo '<p><a class="btn btn-primary btn-md text-white" href="#">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/urgent.svg"  class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Шуурхай зээл</h3>';
echo '<p>Иргэд болон ААН-үүдэд зориулсан хугацаатай хуримтлал үүсгэх боломжийг санал болгож байна.</p>';
echo '<p><a class="btn btn-primary btn-md text-white" href="#">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/car.svg"  class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Автомашин худалдан авах зээл</h3>';
echo '<p>Иргэд болон ААН-үүдэд автомашин худалдан авахад нь зориулсан зээлийн бүтээгдэхүүнийг санал болгож байна.</p>';
echo '<p><a class="btn btn-primary btn-md text-white" href="#">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="100">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/004-cart.svg"  class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Бизнесийн зээлийн шугам</h3>';
echo '<p>Зээлийн төлбөрөө хугацаанд нь төлдөг, эргэлтийн хөрөнгийн санхүүжилт тогтмол шаардагддаг зээлдэгчиддээ зээлийн шугамын эрх нээж, санхүүжилтийн хамгийн таатай нөхцлүүдийг санал болгож байна.</p>';
echo '<p ><a class="btn btn-primary btn-md text-white" href="#">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">';
echo '<div class="unit-4">';
echo '<div class="unit-4-icon">';
echo '<img src="images/flaticon-svg/svg/trust.svg" class="img-fluid w-25 mb-4">';
echo '</div>';
echo '<div>';
echo '<h3>Итгэлцэлийн үйлчилгээ</h3>';
echo '<p>Иргэд болон ААН-үүдэд зориулсан хугацаатай хуримтлал үүсгэх боломжийг санал болгож байна</p>';
echo '<p ><a class="btn btn-primary btn-md text-white" href="#">Дэлгэрэнгүй</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
?>