<?php
echo '<section class="site-section bg-light" id ="ser-section">';
echo '<div class="container">';
echo '<div class="row mb-5 justify-content-center">';
echo '<div class="col-md-7 text-center">';
echo '<h2 class="section-title mb-3" data-aos="fade-up" data-aos-delay="">Үйлчилгээ</h2>';
echo '<p class="lead" data-aos="fade-up" data-aos-delay="100">Бид та бүхэнд дараах үйлчилгээнүүдийг санал болгож байна.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row align-items-lg-center" >';
echo '<div class="col-lg-6 mb-5" data-aos="fade-up" data-aos-delay="">';
echo '<div class="owl-carousel slide-one-item-alt">';
echo '<img src="images/advice1.png" alt="Image" class="img-fluid">';
echo '<img src="images/advice.jpg" alt="Image" class="img-fluid">';
echo '<img src="images/factor.jpg" alt="Image" class="img-fluid">';
echo '<img src="images/batalgaa.jpg" alt="Image" class="img-fluid">';
echo '</div>';
echo '<div class="custom-direction">';
echo '<a href="#" class="custom-prev">';
echo '<span>';
echo '<span class="icon-keyboard_backspace">';
echo '</san>';
echo '</span>';
echo '</a>';
echo '<a href="#" class="custom-next">';
echo '<span>';
echo '<span class="icon-keyboard_backspace">';
echo '</span>';
echo '</span>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">';
echo '<div class="owl-carousel slide-one-item-alt-text">';
echo '<div>';
echo '<h2 class="section-title mb-3">САНХҮҮГИЙН ЗӨВЛӨХ ҮЙЛЧИЛГЭЭ</h2>';
echo '<p>Жижиг дунд бизнесүүдэд зориулсан санхүүгийн удирдлагын зөвлөгөө, мэдээлэл өгөх</p>';
echo '<p>Татварын болон санхүүгийн тайлан тэнцэл гаргах, зөвлөгөө мэдээлэл өгөх</p>';
echo '<p>Нягтлан бодох бүртгэлийн журам боловсруулах, зөвлөгөө мэдээлэл өгөх</p>';
echo '<p>Татвар ба нийгмийн даатгалын шимтгэлийн талаар зөвлөгөө, мэдээлэл өгөх</p>';
echo '<!--<p><a href="#" class="btn btn-primary mr-2 mb-2">Дэлгэрэнгүй</a></p>-->';
echo '</div>';
echo '<div>';
echo '<h2 class="section-title mb-3">ХӨРӨНГӨ ОРУУЛАЛТЫН ЗӨВЛӨХ ҮЙЛЧИЛГЭЭ</h2>';
echo '<p>Гадны компанийн Монголын зах зээлд нэвтрэхэд шаардлагатай зах зээл, үнэ, харилцагчийн судалгаа шинжилгээ хийх</p>';
echo '<p>Хөрөнгө оруулалтын төсөл боловсруулах, зөвлөгөө мэдээлэл өгөх</p>';
echo '<!--<p><a href="#" class="btn btn-primary mr-2 mb-2">Дэлгэрэнгүй</a></p>-->';
echo '</div>';
echo '<div>';
echo '<h2 class="section-title mb-3">ФАКТОРИНГИЙН ҮЙЛЧИЛГЭЭ</h2>';
echo '<p>3 сар хүртэлх хугацаатай авлагыг санхүүжүүлэх үйлчилгээ үзүүлж байна.</p>';
echo '<!--<p><a href="#" class="btn btn-primary mr-2 mb-2">Дэлгэрэнгүй</a></p>-->';
echo '</div>';
echo '<div>';
echo '<h2 class="section-title mb-3">ТӨЛБӨРИЙН БАТАЛГАА ГАРГАХ ҮЙЛЧИЛГЭЭ</h2>';
echo '<p>Хувь хүн, ААН-ууд тендерт оролцох, банкнаас зээл авах, төсөл хөтөлбөрт хамрагдахад дэмжлэг үзүүлэх зорилгоор Банк бус санхүүгийн байгууллагаас төлбөрийн баталгаа гаргах үйлчилгээг үзүүлж байна.</p>';
echo '<!--<p><a href="#" class="btn btn-primary mr-2 mb-2">Дэлгэрэнгүй</a></p>-->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
?>